In [1]:
import numpy as np

In [2]:

arr = np.arange(2, 50, 3)
print(arr)



[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [3]:


list1 = [] 
list2 = []
print("Enter 5 elements for list 1 : ")
for i in range(0, 5): 
    e1 = int(input()) 
    list1.append(e1) 
      


print("Enter 5 elements for list 2 : ")
for i in range(0, 5): 
    e2 = int(input()) 
    list2.append(e2)

print("Elements of list 1 are: ",list1)
print("Elements of list 2 are: ",list2)

arr1 = np.array(list1)
arr2 = np.array(list2)

arr = np.concatenate((arr1,arr2),axis=None)
print("Concatenated array :", arr)

print("Sorted array : ",np.sort(arr))



Enter 5 elements for list 1 : 
1
10
2
9
3
Enter 5 elements for list 2 : 
8
4
7
5
6
Elements of list 1 are:  [1, 10, 2, 9, 3]
Elements of list 2 are:  [8, 4, 7, 5, 6]
Concatenated array : [ 1 10  2  9  3  8  4  7  5  6]
Sorted array :  [ 1  2  3  4  5  6  7  8  9 10]


In [4]:

arr = np.array([[1,9,4],[2,8,5],[3,7,6]])

print("The array is : \n", arr)

print("Dimension of the array is : ", arr.ndim)

print("Size of the array is : ",arr.size)

print("Shape of the array is :", arr.shape)



The array is : 
 [[1 9 4]
 [2 8 5]
 [3 7 6]]
Dimension of the array is :  2
Size of the array is :  9
Shape of the array is : (3, 3)


In [5]:
#array containing 5 elements

arr = np.arange(5)
print(arr)

print("Shape of arr : ", arr.shape)
print("Dimension of the arr is : ", arr.ndim)

#converting 1d array to 2d using np.newaxis
arr1 = arr[:,np.newaxis]

print("Shape of arr1 :", arr1.shape)
print("Dimension of the arr1 is : ", arr1.ndim)

#converting 1d array to 2d using np.expand_dims
arr2 = np.expand_dims(arr, axis=0)

print("Shape of arr2 :", arr2.shape)
print("Dimension of the arr2 is : ", arr2.ndim)



[0 1 2 3 4]
Shape of arr :  (5,)
Dimension of the arr is :  1
Shape of arr1 : (5, 1)
Dimension of the arr1 is :  2
Shape of arr2 : (1, 5)
Dimension of the arr2 is :  2


In [6]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2 = np.array([[4,5,6],[7,8,9],[1,2,3]])

print("arr1 is : \n", arr1)
print("arr2 is : \n", arr2)

print("Vertically Stack: \n", np.vstack((arr1,arr2)))

print("Horizantally Stack: \n", np.hstack((arr1,arr2)))


arr1 is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2 is : 
 [[4 5 6]
 [7 8 9]
 [1 2 3]]
Vertically Stack: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
Horizantally Stack: 
 [[1 2 3 4 5 6]
 [4 5 6 7 8 9]
 [7 8 9 1 2 3]]


In [7]:

arr = np.array([5,10,15,2,10,5,20,5])

unique_item, count = np.unique(arr,return_counts = True)

print("Unique items in arr: \n",unique_item)
print("Count of the unique items: \n",count)


Unique items in arr: 
 [ 2  5 10 15 20]
Count of the unique items: 
 [1 3 2 1 1]
